services:
  db:
    image: postgres:12
    restart: always
    env_file:
      - .development.env
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context:  .
      dockerfile: Dockerfile
    container_name: matryca-lyosu-backend
    env_file:
      - .development.env
    ports:
      - 5000:5000
    depends_on:
      - db
    volumes:
      - ./src:/app/src

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: matryca-pgadmin
    env_file:
      - .development.env
    ports:
      - '5050:80'
    depends_on:
      - db
